### ISSUE TITLE
Getting backup found after entering otp.

### ISSUE THREAD

**Issue by dhruvparmar2310** [sumithemmadi/truecallerjs#11]
I am working on Android Termux, and it was working properly one time, but suddenly when I tried after three days to login again. And when I tried to enter my otp,  the message was "backup found". So how to take backup in termux for truecallerjs. 

And by the way, truecallerjs is an amazing package, which I found during learning duration, and it was also useful before when there was not having any issue with me...

Thank you ! Have a nice day there...

**Comment by sumithemmadi** [comment]
You have linked to your Google account to Truecaller to backup your Truecaller app data for that you need to unlink your Google account from Truecaller app and delete created backups from Truecaller and Google drive

(or)

Or try this steps

Now you can login with json file.

1. On Truecaller App, tap on the 3 line menu on top left.
2. Tap on Privacy Center and then click on Download my data.
3. Now a json file is downloaded.
4. Save the json file on your PC at any location e.g /home/HP/1234567890-99123456789.json
5. On you terminal or command prompt enter below command.

```
~$ truecallerjs login /home/HP/1234567890-99123456789.json
```

7. Now you are successfully logged in.

**Comment by tkhquang** [comment]
How do I unlink the google account? I've tried deleting the data in google drive but still it didn't work
