### ISSUE TITLE
Need documentation For Login & get installation id

### ISSUE THREAD

**Issue by Denver1997** [sumithemmadi/truecallerjs#12]
Need documentation For Login & get installation id

like this

 const truecallerjs = require('truecallerjs');

var searchData = {
    number: "[PHONE_NUMBER]",
    countryCode: "[COUNTRY_CODE]",
    installationId: "[INSTALLATION_ID]"
}

var sn = truecallerjs.searchNumber(searchData);
sn.then(function(response) {
    console.log(response)
});

**Comment by sumithemmadi** [comment]
You can use this it will automatically reads the installationId
```js
const truecallerjs = require('truecallerjs');
const path = require("path");
const fs = require("fs");

const file = path.join(process.env.HOME || process.env.HOMEPATH, ".config", "truecallerjs", "authkey.json")

function read_file(file) {
    try {
        const data = fs.readFileSync(file, "utf8");
        return JSON.parse(data);
    } catch (err) {
        console.error(err)
    }
}

let jsonAuthKey = read_file(file);


var searchData = {
    number: "9912345678",
    countryCode: "IN",
    installationId: jsonAuthKey.installationId,
    output: "JSON"
}

var sn = truecallerjs.searchNumber(searchData);
sn.then(function (response) {
    console.log(response)
});

```

**Comment by Denver1997** [comment]
Sir you didn't understand my concern

I say that how i create installation id

**Comment by sumithemmadi** [comment]
I will add that  in next version of truecallerjs
