### ISSUE TITLE
i'm unable to generate installation ID with browser request

### ISSUE THREAD

**Issue by getsettalk** [sumithemmadi/truecallerjs#13]
Sir I want to know to generate installation ID with GUI tool , mean **hit link By POST Request** and send OTP than verify and get My installation id. 

can you teach me how can achive that .

When We hit That API than we get this Response:
`  data: { status: 40001, message: 'Invalid body format' }`

I have requested Like This :
`  method: 'post',
      url: 'https://account-asia-south1.truecaller.com/v2/sendOnboardingOtp',
      data: '{"countryCode":142,"dialingCode":356,"installationDetails":{"app":{"buildVersion":7,"majorVersion":12,"minorVersion":7,"store":"GOOGLE_PLAY"},"device":{"deviceId":"uqss8ajpzw1nf20z","language":"en","manufacturer":"Realme","model":"Redmi 9A","osName":"Android","osVersion":"10","mobileServices":["GMS"]},"language":"en"},"phoneNumber":917000000002,"region":"region-2","sequenceNo":2}'
    },`

**Comment by sumithemmadi** [comment]
Make sure that content-type is application/json

**Comment by getsettalk** [comment]
Yeah , i have added content-type is application/json . But we don't get valid response.
Can you share that code which can we use generate installation id via post request from chrome browser.
