### ISSUE TITLE
Showing Error

### ISSUE THREAD

**Issue by diligent-coder-MANISH** [sumithemmadi/truecallerjs#15]
{
  "responseStatus": "error",
  "errorResp": "Request failed with status code 426",
  "data": "null"
}

"I have also tried logging in again but showing same error"

**Comment by sumithemmadi** [comment]
Your login may expired

**Comment by diligent-coder-MANISH** [comment]
Already tried logging many times.

**Comment by sumithemmadi** [comment]
follow this https://github.com/sumithemmadi/truecallerjs#login 
use truecaller file to login and try again
