### ISSUE TITLE
Cannot use bulk search, "errorResp": "Request failed with status code 400"

### ISSUE THREAD

**Issue by Handi2290** [sumithemmadi/truecallerjs#16]
![image](https://user-images.githubusercontent.com/54350360/219661001-5a0ce8f2-2a01-4c53-a284-6e5b8da83105.png)

**Comment by sumithemmadi** [comment]
As per your screenshot, you are not passing any phone number.
see this https://github.com/sumithemmadi/truecallerjs#to-make-a-bulk-number-search

As per your question there might be any unknown error from your side.
please try to reinstall truecallerjs and try again
