### ISSUE TITLE
Can you tell what is the exact limit per Installation ID

### ISSUE THREAD

**Issue by Bharath1807** [sumithemmadi/truecallerjs#18]
Can you tell what is the exact limit per Installation ID?
i have tried in many ways but true-caller is restricted my installation id for less than 100 numbers
**Could you please suggest me** how to achieve minimum 10000 numbers per day in any manner

**Comment by sumithemmadi** [comment]
You should use multiple installation IDs and should use bulksearch, I guess around 30 phone numbers.
Once I searched 100 phone numbers
![image](https://user-images.githubusercontent.com/50250422/208607041-b37798a9-e66e-4e41-8773-fc6443ec40cf.jpg)
