### ISSUE TITLE
not generating otp 

### ISSUE THREAD

**Issue by getsettalk** [sumithemmadi/truecallerjs#19]
sir i want to generate otp and process for installation id through my website how to do that 
can you provide me api and any other information with code.

**Comment by sumithemmadi** [comment]
i will add it in next version

**Comment by getsettalk** [comment]
Thank you for your response, i will wait

**Comment by sumithemmadi** [comment]
Your issue resolved.

see this https://github.com/sumithemmadi/truecallerjs#implement-login-function

for more information [https://github.com/sumithemmadi/truecallerjs/tree/main/docs](https://github.com/sumithemmadi/truecallerjs/tree/main/test/#login)
