### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by jeffnyauke** [sumithemmadi/truecallerjs#20]
Keep getting this json response when searching for a number:

```
{
  "responseStatus": "error",
  "errorResp": "Request failed with status code 401",
  "data": "null"
}
```

**Comment by sumithemmadi** [comment]
your previous login maybe expired. try login again.
or try this method 
If you still facing problems in login then try below steps.

On Truecaller Android, tap on the 3 line menu on top left then click on setting's.
Tap on Privacy Center and then click on Download my data.
Now a json file is downloaded.
Save the json file on your PC at any location e.g /home/HP/1234567890-99123456789.json
On you terminal or command prompt enter below command.
