### ISSUE TITLE
ERROR : Request failed with status code 451

### ISSUE THREAD

**Issue by djmeero** [sumithemmadi/truecallerjs#22]
As the title says I'm unable to login.... by using OTP I get this error:
    data: {
      status: 45101,
      message: 'Unavailable for legal reasons',
      domain: 'eu'
    }
By using alternative method with .json file on number lookup I get "ERROR : Request failed with status code 451"

I think it has something to do with Truecaller's EU tokens...because I logged in succesful by using Asian phone number token of a friend. but on italian phone number lookup the result is:

data            :
id              : 4hVlep08gyBufaUI0hhPFw==
access          : PUBLIC
enhanced        : true
phones          :
e164Format      : +39320XXXXXXX
numberType      : MOBILE
nationalFormat  : 320 XXX XXXX
dialingCode     : 39
countryCode     : IT
carrier         : Wind Tre S.p.A.
type            : openPhone
addresses       :
countryCode     : IT
type            : address
internetAddresses : []
badges          : []
tags            : []
cacheTtl        : 86400000
sources         : []
searchWarnings  : []
surveys         :
id              : 100
frequency       : 3600
passthroughData : eyAiMyI6ICIzOTMyMDk3MzQ4NTYiIH0=
perNumberCooldown : 7890000
id              : b6588ff4-47cb-46ce-8b11-015199c1f729
frequency       : 3600
passthroughData : eyAiMyI6ICIzOTMyMDk3MzQ4NTYiIH0=
perNumberCooldown : 7890000
commentsStats   :
showComments    : false
ns              : 100
provider        : ss-nu
stats           :
sourceStats     : []

I get just carrier info, looks like the "data" field containing the name is missing...

**Comment by sumithemmadi** [comment]
are you able use truecaller app on your phone  ?
if yes then are you able to get the name of the person with same phone number ?

**Comment by djmeero** [comment]
Yes, sure, it works perfectly fine.
