### ISSUE TITLE
cant login to my truecaller account & i cant find my installation id in the json file

### ISSUE THREAD

**Issue by El3omda** [sumithemmadi/truecallerjs#24]
cant login to my truecaller account & i cant find my installation id in the json file thats include my account data

**Comment by Navitas28** [comment]
same issue

**Comment by sumithemmadi** [comment]
Which country phone number are you using ?

**Comment by Navitas28** [comment]
India , it says backup found
<img width="509" alt="Screenshot 2023-05-28 at 15 01 40" src="https://github.com/sumithemmadi/truecallerjs/assets/8795442/96bccd0f-d05b-4ff4-9e34-84d0bd37dfb7">

**Comment by Navitas28** [comment]
I
<img width="509" alt="Screenshot 2023-05-28 at 15 01 40" src="https://github.com/sumithemmadi/truecallerjs/assets/8795442/e288f2e6-e856-40a9-88c6-894305e00442">
ndia , it says backup found

**Comment by sumithemmadi** [comment]
@Navitas28 
 You have linked  your Google account to Truecaller to backup your Truecaller app data.If you still want to use Truecallerjs ,  you need to unlink your Google account from Truecaller app and delete created backups from Truecaller and Google drive
