### ISSUE TITLE
Error: Cannot find module '/root/****/node_modules/truecallerjs/dist/axios.cjs'

### ISSUE THREAD

**Issue by L337C0D3R** [sumithemmadi/truecallerjs#25]

**Comment by sumithemmadi** [comment]
Sorry, It was a mistake I will update it. I will close this issue after I make an update.

**Comment by sumithemmadi** [comment]
truecallerjs@2.0.1  version contain some bugs and errors ,please use version  1.1.5 as of now or wait for the next update.
