### ISSUE TITLE
"AxiosError" - "Request failed with status code 429"

### ISSUE THREAD

**Issue by RVedang** [sumithemmadi/truecallerjs#28]
When I'm trying bulk search, I'm getting error shown below. However, a single number search works perfectly fine.

![image](https://github.com/sumithemmadi/truecallerjs/assets/74816544/a4d28b44-b61b-47a2-8fb8-82ff2aeb87f3)

**Comment by sumithemmadi** [comment]
Similar to #6 

Please read this [Limitations](http://github.com/sumithemmadi/truecallerjs#limitations)
