### ISSUE TITLE
No OTP received

### ISSUE THREAD

**Issue by ahmedh-i** [sumithemmadi/truecallerjs#29]
I tried to run the following command `truecallerjs login` in order to get the OTP code, but I'm receiving a phone call verification each time instead of an OTP code.

I'm using a phone number inside Egypt. 

UPDATE: I tried older versions (1.1.2 & 1.1.5) and had the same issue, even though login with the JSON file didn't work, it throws an exception, I think because the installation id is no longer exist in the JSON file.

**Comment by sumithemmadi** [comment]
The problem lies with certain African countries where Truecaller is utilizing a different API for login purposes. The data type used in this case is gRPC. Therefore, I require some proto files to implement the functionality. The login functionality for this countries will be made available soon.

**Comment by Zapotaya** [comment]
same problem, I live in belgium and when i put +32 international format i'have the script wich executes...

**Comment by yhimanshu-yadav** [comment]
I am from Nepal. I have tried many times and every time it says verification failed. Then, I tried my friend's number in the US, and the same error was seen "Verification Failed". Please Help me figure it out.

**Comment by Sameer07x19** [comment]
I am encountering this same issue and i am from india

**Comment by RAGEHITMAN47** [comment]
> I am encountering this same issue and i am from india

you got the solution

**Comment by dare-tunmise** [comment]
From Nigeria. Getting "verification failed." Even subscribed to premium truecaller. Sigh
