### ISSUE TITLE
You have exceeded the limit of verification attempts.  Please try again after some time.

### ISSUE THREAD

**Issue by roysG** [sumithemmadi/truecallerjs#36]
Hi,
I success to login once and i get the "Backup Found".
I read that i need to remove the connect to google and disable backup.

I did all there steps and i tried again..

But now i get the error:

Sending OTP to +972502118551.
You have exceeded the limit of verification attempts.
Please try again after some time.

What should i do?

(I tried to remove the app in the android phone and install again. But the error is the same)

**Comment by roysG** [comment]
Ok, after some time i can get OTP again. but i do not understand how to full disconnect the truecaller from google account

Someone can write some steps?

Thanks

**Comment by sumithemmadi** [comment]
[Deactivate](https://support.truecaller.com/support/solutions/articles/81000392559-how-do-i-deactivate-and-delete-my-truecaller-account-#:~:text=As%20a%20user%2C%20you%20have,menu%20within%20the%20Truecaller%20app.) your Truecaller account and try to login with truecallerjs
