### ISSUE TITLE
AxiosError: Request failed with status code 400

### ISSUE THREAD

**Issue by siddhantshubham2001** [sumithemmadi/truecallerjs#37]
truecallerjs --s +919912345678,9912584758

message             : Request failed with status code 400
name                : AxiosError
stack               : AxiosError: Request failed with status code 400
    at settle (file:///C:/Users/user/AppData/Roaming/npm/node_modules/truecallerjs/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (file:///C:/Users/user/AppData/Roaming/npm/node_modules/truecallerjs/node_modules/axios/lib/adapters/http.js:570:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
config              :
transitional        :
silentJSONParsing   : true
forcedJSONParsing   : true
clarifyTimeoutError : false
adapter             : xhr, http
transformRequest    : null
transformResponse   : null
timeout             : 0
xsrfCookieName      : XSRF-TOKEN
xsrfHeaderName      : X-XSRF-TOKEN
maxContentLength    : -1
maxBodyLength       : -1
env                 : {}
headers             :
Accept              : application/json, text/plain, */*
content-type        : application/json; charset=UTF-8
accept-encoding     : gzip
user-agent          : Truecaller/11.75.5 (Android;10)
Authorization       : Bearer a1i0g--gpbRJ1VF-cJZ5ZMB2m6vlOttvURo8dUfMixU9IDwAxxxxxxxxxxxxxx
params              :
countryCode         : IN
type                : 4
locAddr             :
placement           : SEARCHRESULTS,HISTORY,DETAILS
encoding            : json
method              : get
url                 : https://search5-noneu.truecaller.com/v2/search
code                : ERR_BAD_REQUEST
status              : 400

**Comment by sumithemmadi** [comment]
truecallerjs --s "+919912345678,9912584758"
