### ISSUE TITLE
Error: Back up found [ status : 17 ] 

### ISSUE THREAD

**Issue by RabbitFored** [sumithemmadi/truecallerjs#38]
I get this error while login using truecallerjs:

`{"status":17,"message":"Back up found","userId":9104xxxxxx53472,"requestId":"12422xxxxxxxxxxxf0d0","backupTime":1636871584101}`

And I get this while I login using official TrueCaller app:

![photo_2023-07-24_11-03-49](https://github.com/sumithemmadi/truecallerjs/assets/73241991/eb7088d1-439e-4e9b-abd8-1c05a605ba0c)

**Comment by RabbitFored** [comment]
Anyway to do this programmatically?

**Comment by sumithemmadi** [comment]
Similar to #11
