### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by Lawny61** [sumithemmadi/truecallerjs#39]
Hello there i wanted to enquire if there are rate limits per a logged in account ?

**Comment by shailendramaurya** [comment]
Truecaller only have search rate limit on their web API, not on it's app....... and this script utilises it's Android app API and pretends to be a real trucaller application

**Comment by sumithemmadi** [comment]
If you have lost your key and are unable to log in, you can regain access within one hour. However, if you attempt to log in too frequently and exceed the allowed number of attempts, you will be temporarily blocked. In such a case, you will be allowed to try logging in again after 13 hours.

For normal phone number searches, you are limited to searching for less than 100 phone numbers per day.

For bulk searches, you can search for 30 phone numbers per request, and you are allowed to make 5 to 6 requests per day.

For more https://github.com/sumithemmadi/truecallerjs#limitations
