### ISSUE TITLE
Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by ameeraz19** [sumithemmadi/truecallerjs#40]
**when i use command for example:**
truecallerjs -s 527607844 -n
**or**
truecallerjs -s 527607844 
**or even** 
truecallerpy -s 527607844

**after 47 tries its return** 
Cannot read properties of undefined (reading '0'). **or** Expecting value: line 1 column 1 (char 0).

i think that the problem from truecaller server which had a limit for phone number lookup, can you help to exceed the limit i search for truecaller api every where but the have nothing for js or python im looking to pay per search ...

**Comment by sumithemmadi** [comment]
@ameeraz19  https://github.com/sumithemmadi/truecallerjs/issues/39#issuecomment-1666734931 reed this comment.
