### ISSUE TITLE
Login nhi ho rha

### ISSUE THREAD

**Issue by Hackerbhai0007** [sumithemmadi/truecallerjs#44]

**Comment by sumithemmadi** [comment]
Can you share me a screenshot ?
what is the  version of truecallerjs ?
which country phone number are you using ?

**Comment by rudra68** [comment]
I am also same problem
![IMG_20231029_234616.jpg](https://github.com/sumithemmadi/truecallerjs/assets/149326309/4003af93-96b7-4524-8f9f-5d3c2d22e0b3)
