### ISSUE TITLE
TypeError: truecallerjs.searchNumber is not a function

### ISSUE THREAD

**Issue by d3v7** [sumithemmadi/truecallerjs#48]
i am using truecallerjs version 2.2.0 in both windows and linux

in windows it works fine but in linux i am getting this error
`TypeError: truecallerjs.searchNumber is not a function`

**Comment by sumithemmadi** [comment]
`searchNumber`  doesn't exist, use `search` function

here is the example.

```js
import { search } from "truecallerjs";

var data = {
    number: "Phone Number",
    countryCode: "Default Country Code",
    installationId: "Your Installation Id",
};
search(data).then((res) => {
    console.log(JSON.stringify(res, null, 4));
});
```
