### ISSUE TITLE
Your code is compromised because it uses "colors". The author of colors has corrupted the code which is affecting all the apps using it. Please check the link I've added in the description.

### ISSUE THREAD

**Issue by faizanvahevaria** [sumithemmadi/truecallerjs#5]
https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/

**Comment by faizanvahevaria** [comment]
@sumithemmadi I've downloaded the source code and changed colors version to 1.3.0 and ran npm install

now, trying to use this by running node bin/index.js login

**Comment by sumithemmadi** [comment]
Ok i will check it. 
And thanks for reporting.

**Comment by sumithemmadi** [comment]
I have removed **colors** module and updated [truecallerjs...v1.0.7](https://www.npmjs.com/package/truecallerjs)
Now it is working fine.
