### ISSUE TITLE
What is the manimum number of search request we can make in a day ?

### ISSUE THREAD

**Issue by mosfaqur** [sumithemmadi/truecallerjs#53]

**Comment by qinetique** [comment]
i don't think it has a limit. You can search as many as you want even in bulk.

**Comment by sviatoslavPaliy** [comment]
The maximum number of phone numbers that can be checked is 25

**Comment by sumithemmadi** [comment]
see this https://github.com/sumithemmadi/truecallerjs/issues/9 and https://github.com/sumithemmadi/truecallerjs/issues/18
