### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by anaschauhan33** [sumithemmadi/truecallerjs#6]
Hey I am getting the following error
```
{
    "responseStatus": "error",
    "errorResp": "Request failed with status code 429",
    "data": "null"
}
```

**Comment by sumithemmadi** [comment]
if you are trying to  search number too often in a short period of time,truecaller server may send a 429 error,for example if your are sending too many request in a short period of time then server will give a response 429.

The most simple way to avoid this error is to reduce the number of requests made in a short period of time. The server is keeping track of how many requests per time unit you make and will enforce it — leading to a temporary block if exceeded.

And remember, receiving a 429 is not necessarily an error, it’s the server’s way of telling you your rate of requests is too high and not willing to accept those actions.

**Comment by cha0uki** [comment]
How many requests per minute do you advise?
