### ISSUE TITLE
Truecallerjs is not working 

### ISSUE THREAD

**Issue by Ansarisahab** [sumithemmadi/truecallerjs#65]
Truecallerjs is not working
Truecallerjs problem zsh no matches found 
![Screenshot_2023-12-23-14-05-55-623_com termux](https://github.com/sumithemmadi/truecallerjs/assets/148077229/524d2c0b-4bf9-45c3-9edc-06092c3efc79)

**Comment by sumithemmadi** [comment]
see this https://github.com/sumithemmadi/truecallerjs?tab=readme-ov-file#command-line-usage
