### ISSUE TITLE
When I request an OTP, he calls me by phone and does not send the code

### ISSUE THREAD

**Issue by Ahm3dksa** [sumithemmadi/truecallerjs#7]
When I request an OTP, he calls me by phone and does not send the code

**Comment by sumithemmadi** [comment]
What you are saying ?
You are not able to recieve an otp

**Comment by Ahm3dksa** [comment]
yeah,
i recivecd call not msg

**Comment by sumithemmadi** [comment]
What is saying in the call ? 
Which  country you belong to ?
Which operating system are you using ?

**Comment by Ahm3dksa** [comment]
nothing
egypt
windows 11

**Comment by sumithemmadi** [comment]
Will you try again one more time by installing again
```
~$ npm install -g truecallerjs
```

**Comment by sumithemmadi** [comment]
Here is my new update [truecallerjs@1.0.10.](https://www.npmjs.com/package/truecallerjs/v/1.0.10)

Now you can login with json file.

1. On Truecaller App, tap on the 3 line menu on top left.
2. Tap on Privacy Center and then click on Download my data.
3. Now a json file is downloaded.
4. Save the json file on your PC at any location e.g /home/HP/1234567890-99123456789.json
5. On you terminal or command prompt enter below command.

```
~$ truecallerjs login /home/HP/1234567890-99123456789.json
```

7. Now you are successfully logged in.
