### ISSUE TITLE
How many numbers Can See

### ISSUE THREAD

**Issue by ramancs** [sumithemmadi/truecallerjs#8]
Hi, Is there any limit from truecaller for looking a mobile number details via this package using node on a single installation id?

**Comment by sumithemmadi** [comment]
Yes, truecaller have  limited requests per day. ,  truecaller server may send a 429 when they are exceeded.
you can use a bulk search to query many numbers in one request. using a bulk search will  save requests.
https://github.com/sumithemmadi/truecallerjs#to-make-a-bulk-number-search
https://github.com/sumithemmadi/truecallerjs#make-a-bulk-search-in-your-project
