### ISSUE TITLE
How to resolve this error? PS;- I am using visual studio to run my code

### ISSUE THREAD

**Issue by sumit89871** [sumithemmadi/truecallerjs#9]
var sn = truecallerjs.searchNumber(searchData);
                      ^

TypeError: truecallerjs.searchNumber is not a function

**Comment by sumithemmadi** [comment]
Have you included the "truecallerjs" package. if not include in this way.
```js
const truecallerjs = require('truecallerjs');
```


Example:
```js
const truecallerjs = require('truecallerjs');
var searchData = {
    number: "+12093031250",
    countryCode: "IN",
    installationId: "a1k07--Vgdfyvv_rftf5uuudhuhnkljyvvtfftjuhbuijbhug",
    output: "XML"
}

var sn = truecallerjs.searchNumber(searchData);
sn.then(function(response) {
    console.log(response)
});
```

If you still facing the same error , either you have not installed "Truecallerjs" locally on your project folder or you have installed it globally.

In your project root directory install the package.

```bash
npm install truecallerjs
```
- NPM creates a folder named "node_modules", where the truecallerjs package will be placed.
- Once the package is installed, it is ready to use.
- Include the package and use it.
```js
const truecallerjs = require('truecallerjs');
```

**Comment by sumit89871** [comment]
Thanks bro it's working now. I installed the package globally that's why it was not working. I just want to know 1 thing, that I have almost 200k numbers,can I search them all at one go???

**Comment by sumithemmadi** [comment]
No , you cann't because truecaller allows you to check 70 - 100 phone numbers per/day. If you want to check, then you need multiple installation ids.​​​​​
